logging:
    level:
      root: debug
spring:
    devtools:
        restart:
            enabled: true  #设置开启热部署
    #出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
    mvc:
        throw-exception-if-no-handler-found: false
    #不要为我们工程中的资源文件建立映射
    resources:
        add-mappings: false
    application:
      version: 1.0
      description: 通用框架
