server:
    port: 5858
spring:
    application:
        name: adminserver
logging:
    level:
        org.springframework.boot.env.PropertySourcesLoader: TRACE
        org.springframework.web: INFO
management:
    metrics:
        web:
            server:
                request:
                    autotime:
                        enabled: false
eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8887/eureka/,http://127.0.0.1:8888/eureka/,http://127.0.0.1:8889/eureka/
    instance:
        hostname: ${spring.cloud.client.ip-address}
        instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
