pay:
    ali:
        ali-pay-cert-path:
        ali-pay-public-key:
        ali-pay-root-cert-path:
        app-cert-path:
        app-id:
        cert-model:
        cert-type:
        charset:
        domain:
        private-key:
        service-url:
        sign-type:
    paypal:
        client-id:
        domain:
        sand-box:
        secret:
    wx:
        api-key3:
        api-key:
        app-id:
        cert-path:
        cert-pem-path:
        domain:
        ex-params:
        key-pem-path:
        mch-id:
        partner-key:
        platform-cert-path:
        sl-app-id:
        sl-mch-id:
    jd:
        app-id:
        cert-path:
        des-key:
        domain:
        mch-id:
        rsa-private-key:
        rsa-public-key:
