spring:
  main:
    allow-bean-definition-overriding: true

management:
  health:
    defaults:
      enabled: false
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8887/eureka/
#  instance:
#    prefer-ip-address: true
#    hostname: ${spring.cloud.client.ip-address}
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
logging:
  level:
    root: info
    com.alibaba.nacos.client.naming: error
