server:
  port: 3001
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.133.124:30002/flow?useUnicode=true&useSSL=true&nullCatalogMeansCurrent=true
    username: root
    password: uY;:rs623ic&
management:
  health:
    defaults:
      enabled: false
logging:
  level:
    root: debug
  file:
    path: simple4j.log
flowable:
  database-schema-update: true
